server:
  port: 8082

spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    username: "coopmap"
    url: "jdbc:postgresql://postgres:5432/coopmap"
    initialization-mode: always
    initialize: true


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
# to auto create a sql file for schema migration
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#              create-source:  metadata